name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      AWS_REGION: ${{ secrets.AWS_REGION }}
      ECR_REPOSITORY: ${{ secrets.ECR_REPOSITORY }}

    steps:

      # STEP 1
      - name: Checkout Code
        uses: actions/checkout@v4

      # STEP 2
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      # STEP 3
      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      # STEP 4
      - name: Build Docker Image
        run: |
          docker build -t $ECR_REPOSITORY ./app

      # STEP 5
      - name: Tag Docker Image
        run: |
          docker tag $ECR_REPOSITORY:latest \
          ${{ secrets.ECR_REGISTRY }}/$ECR_REPOSITORY:latest

      # STEP 6
      - name: Push Docker Image to ECR
        run: |
          docker push \
          ${{ secrets.ECR_REGISTRY }}/$ECR_REPOSITORY:latest

      # STEP 7
      - name: Force ECS Deployment
        run: |
          aws ecs update-service \
          --cluster ${{ secrets.ECS_CLUSTER }} \
          --service ${{ secrets.ECS_SERVICE }} \
          --force-new-deployment